[build]
builder = "NIXPACKS"
buildCommand = "npm run build && npx tsc --project tsconfig.server.json && npx prisma generate"

[deploy]
startCommand = "npx prisma migrate deploy && node dist/server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
